name: Release

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build FMU
      run: bash build_fmu.sh
    - name: Upload FMU
      uses: softprops/action-gh-release@v2
      with:
        files: dist/SailControlSystem.fmu
